name: "next-semantic-version"
description: "Return the next semantic version number based on commit messages"

outputs:
  next-release:
    description: "Commit will generate a new release or not"
    value: ${{steps.version.outputs.next-release}}
  next-release-version:
    description: "The next version number"
    value: ${{steps.version.outputs.next-release-version}}

runs:
  using: composite
  steps:
    - shell: bash
      id: version
      run: |
        yarn dlx semantic-release --dry-run --no-ci \
          --plugins @semantic-release/commit-analyzer ${{github.action_path}}/semantic-extract-version.cjs \
          --branches ${{github.ref_name}} ${{github.head_ref}}
