name: ""
description: ""

runs:
  using: composite
  steps:
    - shell: bash
      id: version
      run: |
        yarn dlx semantic-release --dry-run \
          --plugins @semantic-release/commit-analyzer ${{github.action_path}}/semantic-extract-version.cjs \
          --branches ${{github.ref_name}}

    - shell: bash
      run: echo ${{steps.version.outputs.next-release}} ${{steps.version.outputs.next-release-version}}
